# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Making It Realm
email: hello@makingitrealm.space
description: >- # this means to ignore newlines until the next variable
  We create things that did not exist before and find motivation by sharing our creations using this space.
callout-html: >- 
  Get notified about the next exhibition <a href="https://www.facebook.com/MakingItRealm">on this page</a>. <br />
  Would like to see your creation here? Join our community of creators <a href="https://www.facebook.com/groups/mircreators">here</a>. <br /><br />
  <a href="https://plausible.io/makingitrealm.space" target="_blank">Privacy friendly analytics</a> is sponsored by the friendly creatures of <a href="https://unka.space" target="_blank">UNKA</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://makingitrealm.space # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# plugins:
#  - jekyll-feed

collections:
  creations:
  authors:
    output: true
  exhibitions:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
